-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKOXTxz+U/z4td8de
QQE7PVncmidmYRidY/hd+oTA0b+gCgYIKoZIzj0DAQehRANCAARLisngIwW4h00m
fEn5+Xiy+XmeUGVtC5wgxKk+1jfUrgZDKSjh6VSKE8hvP4VXs0ampzAWLHmvRtK3
fIryXdiN
-----END PRIVATE KEY-----